### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by yivo** [Dionach/CodeIgniterXor#3]
break.py output:

```
Found cookie - ci_session
Traceback (most recent call last):
  File "breakkey.py", line 109, in <module>
    session = decode(test)
  File "breakkey.py", line 42, in decode
    session += sxor(firstpass[i], firstpass[i+1])
IndexError: string index out of range
```

Tested with:

```
ci_session=a%3A6%3A%7Bs%3A10%3A%22session_id%22%3Bs%3A32%3A%220a13c8b691ba8395ae70af3c88c683cf%22%3Bs%3A10%3A%22ip_address%22%3Bs%3A13%3A%22195.177.74.42%22%3Bs%3A10%3A%22user_agent%22%3Bs%3A100%3A%22zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz%22%3Bs%3A13%3A%22last_activity%22%3Bi%3A1471016009%3Bs%3A9%3A%22user_data%22%3Bs%3A0%3A%22%22%3Bs%3A13%3A%22cart_contents%22%3Ba%3A3%3A%7Bs%3A32%3A%22e369853df766fa44e1ed0ff613f563bd%22%3Ba%3A6%3A%7Bs%3A5%3A%22rowid%22%3Bs%3A32%3A%22e369853df766fa44e1ed0ff613f563bd%22%3Bs%3A2%3A%22id%22%3Bs%3A2%3A%2234%22%3Bs%3A3%3A%22qty%22%3Bs%3A1%3A%221%22%3Bs%3A5%3A%22price%22%3Bs%3A3%3A%22999%22%3Bs%3A4%3A%22name%22%3Bs%3A2%3A%2234%22%3Bs%3A8%3A%22subtotal%22%3Bi%3A999%3B%7Ds%3A11%3A%22total_items%22%3Bi%3A1%3Bs%3A10%3A%22cart_total%22%3Bi%3A999%3B%7D%7Ddbb8b85bf09a621fde2d9f75717c5016; expires=Fri, 12-Aug-2016 17:33:29 GMT; path=/
```

**Comment by rbsec** [comment]
This script is designed to attack XOR encrypted CodeIgniter cookies (see the blog post in the readme for details). The cookie you've given here isn't encrypted - it just has a hash appended - so the script is not going to work.
